version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    volumes:
      - ./data:/app/data

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database_name
    volumes:
      - ./pgdata:/var/lib/postgresql/data

